version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html  # Локальная папка с проектом подключается в контейнер
    ports:
      - "8080:80"  # Порт 80 контейнера доступен на порту 8080 хоста
    environment:
      DB_HOST: sql310.infinityfree.com
      DB_NAME: if0_37950136_supermarket
      DB_USER: if0_37950136
      DB_PASSWORD: t@gx9jy15tX1VF

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sql310.infinityfree.com  # Хост удалённой базы данных
      MYSQL_ROOT_PASSWORD: t@gx9jy15tX1VF  # Пароль от базы данных InfinityFree
    ports:
      - "8081:80"
