version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html  # Локальная папка с проектом подключается в контейнер
    ports:
      - "8080:80"  # Порт 80 контейнера доступен на порту 8080 хоста
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: supermarket
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql  # Хранение данных БД
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Файл для инициализации БД
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"

volumes:
  db_data:  # Определение тома для данных MySQL
