version: '3.8'

services:
  php:
    image: php:8.0-apache
    volumes:
      - ./app:/var/www/html # Připojení lokální složky app do kontejneru
    ports:
      - "8080:80" # Přesměrování portu 80 v kontejneru na port 8080 na hostiteli
    environment:
      - ACCEPT_EULA=Y
    command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground" # Instalace rozšíření PDO a spuštění Apache

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Nastavení hesla pro uživatele root
      MYSQL_DATABASE: supermarket # Vytvoření databáze supermarket
      MYSQL_USER: user # Vytvoření uživatele user
      MYSQL_PASSWORD: user_password # Nastavení hesla pro uživatele user
    volumes:
      - db_data:/var/lib/mysql # Volume pro ukládání dat MySQL
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Inicializační SQL soubor
    ports:
      - "3306:3306" # Přesměrování portu 3306 v kontejneru na port 3306 na hostiteli

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db # Název služby MySQL (db)
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80" # Přesměrování portu 80 v kontejneru na port 8081 na hostiteli

volumes:
  db_data: # Definice volume pro ukládání dat MySQL